services:
  php:
    image: docker_zofto_php_backend
    container_name: docker_php_backend
    build: .
    ports:
      - 8001:8000
    volumes:
      - ./:/Zofto/zofto-api
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - '3306:3306'

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    depends_on:
        - db
    ports:
      - "8081:80"